// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: grpcserver/proto/ai_gateway.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiGateway_GenerateStream_FullMethodName        = "/ai_gateway.AiGateway/GenerateStream"
	AiGateway_FetchAvailableModels_FullMethodName  = "/ai_gateway.AiGateway/FetchAvailableModels"
	AiGateway_ValidateModel_FullMethodName         = "/ai_gateway.AiGateway/ValidateModel"
	AiGateway_ForwardChatCompletion_FullMethodName = "/ai_gateway.AiGateway/ForwardChatCompletion"
)

// AiGatewayClient is the client API for AiGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AiGateway gRPC 服务定义
// 供 Java 服务内部调用 Go AI Gateway 的 AI 能力
type AiGatewayClient interface {
	// 流式生成：Java 调用 Go 获取 AI 流式结果
	GenerateStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error)
	// 获取用户可用模型列表
	FetchAvailableModels(ctx context.Context, in *ModelsRequest, opts ...grpc.CallOption) (*ModelsResponse, error)
	// 模型连通性验证
	ValidateModel(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	// Chat Completion 转发：Java 发送完整请求体，Go 转发给 AI 厂商
	// 用于 Function Calling 场景，工具执行在 Java 端，LLM 调用走 Go
	ForwardChatCompletion(ctx context.Context, in *ForwardChatRequest, opts ...grpc.CallOption) (*ForwardChatResponse, error)
}

type aiGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAiGatewayClient(cc grpc.ClientConnInterface) AiGatewayClient {
	return &aiGatewayClient{cc}
}

func (c *aiGatewayClient) GenerateStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiGateway_ServiceDesc.Streams[0], AiGateway_GenerateStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiGateway_GenerateStreamClient = grpc.ServerStreamingClient[StreamChunk]

func (c *aiGatewayClient) FetchAvailableModels(ctx context.Context, in *ModelsRequest, opts ...grpc.CallOption) (*ModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelsResponse)
	err := c.cc.Invoke(ctx, AiGateway_FetchAvailableModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiGatewayClient) ValidateModel(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, AiGateway_ValidateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiGatewayClient) ForwardChatCompletion(ctx context.Context, in *ForwardChatRequest, opts ...grpc.CallOption) (*ForwardChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardChatResponse)
	err := c.cc.Invoke(ctx, AiGateway_ForwardChatCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiGatewayServer is the server API for AiGateway service.
// All implementations must embed UnimplementedAiGatewayServer
// for forward compatibility.
//
// AiGateway gRPC 服务定义
// 供 Java 服务内部调用 Go AI Gateway 的 AI 能力
type AiGatewayServer interface {
	// 流式生成：Java 调用 Go 获取 AI 流式结果
	GenerateStream(*StreamRequest, grpc.ServerStreamingServer[StreamChunk]) error
	// 获取用户可用模型列表
	FetchAvailableModels(context.Context, *ModelsRequest) (*ModelsResponse, error)
	// 模型连通性验证
	ValidateModel(context.Context, *ValidateRequest) (*ValidateResponse, error)
	// Chat Completion 转发：Java 发送完整请求体，Go 转发给 AI 厂商
	// 用于 Function Calling 场景，工具执行在 Java 端，LLM 调用走 Go
	ForwardChatCompletion(context.Context, *ForwardChatRequest) (*ForwardChatResponse, error)
	mustEmbedUnimplementedAiGatewayServer()
}

// UnimplementedAiGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiGatewayServer struct{}

func (UnimplementedAiGatewayServer) GenerateStream(*StreamRequest, grpc.ServerStreamingServer[StreamChunk]) error {
	return status.Error(codes.Unimplemented, "method GenerateStream not implemented")
}
func (UnimplementedAiGatewayServer) FetchAvailableModels(context.Context, *ModelsRequest) (*ModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchAvailableModels not implemented")
}
func (UnimplementedAiGatewayServer) ValidateModel(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateModel not implemented")
}
func (UnimplementedAiGatewayServer) ForwardChatCompletion(context.Context, *ForwardChatRequest) (*ForwardChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardChatCompletion not implemented")
}
func (UnimplementedAiGatewayServer) mustEmbedUnimplementedAiGatewayServer() {}
func (UnimplementedAiGatewayServer) testEmbeddedByValue()                   {}

// UnsafeAiGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiGatewayServer will
// result in compilation errors.
type UnsafeAiGatewayServer interface {
	mustEmbedUnimplementedAiGatewayServer()
}

func RegisterAiGatewayServer(s grpc.ServiceRegistrar, srv AiGatewayServer) {
	// If the following call panics, it indicates UnimplementedAiGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiGateway_ServiceDesc, srv)
}

func _AiGateway_GenerateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiGatewayServer).GenerateStream(m, &grpc.GenericServerStream[StreamRequest, StreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiGateway_GenerateStreamServer = grpc.ServerStreamingServer[StreamChunk]

func _AiGateway_FetchAvailableModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiGatewayServer).FetchAvailableModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiGateway_FetchAvailableModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiGatewayServer).FetchAvailableModels(ctx, req.(*ModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiGateway_ValidateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiGatewayServer).ValidateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiGateway_ValidateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiGatewayServer).ValidateModel(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiGateway_ForwardChatCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiGatewayServer).ForwardChatCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiGateway_ForwardChatCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiGatewayServer).ForwardChatCompletion(ctx, req.(*ForwardChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiGateway_ServiceDesc is the grpc.ServiceDesc for AiGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_gateway.AiGateway",
	HandlerType: (*AiGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchAvailableModels",
			Handler:    _AiGateway_FetchAvailableModels_Handler,
		},
		{
			MethodName: "ValidateModel",
			Handler:    _AiGateway_ValidateModel_Handler,
		},
		{
			MethodName: "ForwardChatCompletion",
			Handler:    _AiGateway_ForwardChatCompletion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateStream",
			Handler:       _AiGateway_GenerateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpcserver/proto/ai_gateway.proto",
}
