// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: grpcserver/proto/ai_gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChunkType 响应块类型
type ChunkType int32

const (
	ChunkType_CONTENT   ChunkType = 0 // 正式回答内容
	ChunkType_REASONING ChunkType = 1 // 深度思考/推理过程
	ChunkType_TOOL_CALL ChunkType = 2 // 工具调用
	ChunkType_DONE      ChunkType = 3 // 流结束标识
)

// Enum value maps for ChunkType.
var (
	ChunkType_name = map[int32]string{
		0: "CONTENT",
		1: "REASONING",
		2: "TOOL_CALL",
		3: "DONE",
	}
	ChunkType_value = map[string]int32{
		"CONTENT":   0,
		"REASONING": 1,
		"TOOL_CALL": 2,
		"DONE":      3,
	}
)

func (x ChunkType) Enum() *ChunkType {
	p := new(ChunkType)
	*p = x
	return p
}

func (x ChunkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcserver_proto_ai_gateway_proto_enumTypes[0].Descriptor()
}

func (ChunkType) Type() protoreflect.EnumType {
	return &file_grpcserver_proto_ai_gateway_proto_enumTypes[0]
}

func (x ChunkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkType.Descriptor instead.
func (ChunkType) EnumDescriptor() ([]byte, []int) {
	return file_grpcserver_proto_ai_gateway_proto_rawDescGZIP(), []int{0}
}

// StreamRequest 流式生成请求
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ConfigId      int64                  `protobuf:"varint,4,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"` // 可选，指定配置 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_grpcserver_proto_ai_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StreamRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StreamRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *StreamRequest) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

// StreamChunk 流式响应的单个文本片段
type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkType     ChunkType              `protobuf:"varint,1,opt,name=chunk_type,json=chunkType,proto3,enum=ai_gateway.ChunkType" json:"chunk_type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_grpcserver_proto_ai_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *StreamChunk) GetChunkType() ChunkType {
	if x != nil {
		return x.ChunkType
	}
	return ChunkType_CONTENT
}

func (x *StreamChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ModelsRequest 获取可用模型请求
type ModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      int64                  `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsRequest) Reset() {
	*x = ModelsRequest{}
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsRequest) ProtoMessage() {}

func (x *ModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsRequest.ProtoReflect.Descriptor instead.
func (*ModelsRequest) Descriptor() ([]byte, []int) {
	return file_grpcserver_proto_ai_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ModelsRequest) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

// ModelsResponse 可用模型响应
type ModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []string               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsResponse) Reset() {
	*x = ModelsResponse{}
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsResponse) ProtoMessage() {}

func (x *ModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsResponse.ProtoReflect.Descriptor instead.
func (*ModelsResponse) Descriptor() ([]byte, []int) {
	return file_grpcserver_proto_ai_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ModelsResponse) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

// ValidateRequest 模型验证请求
type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      int64                  `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_grpcserver_proto_ai_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateRequest) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

// ValidateResponse 模型验证响应
type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_grpcserver_proto_ai_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ForwardChatRequest Chat Completion 转发请求
type ForwardChatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigId        int64                  `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`                       // 用户模型配置 ID（Go 端查配置获取 apiKey/baseUrl/provider）
	RequestBodyJson string                 `protobuf:"bytes,2,opt,name=request_body_json,json=requestBodyJson,proto3" json:"request_body_json,omitempty"` // 完整的 OpenAI 格式请求体 JSON（含 messages + tools）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ForwardChatRequest) Reset() {
	*x = ForwardChatRequest{}
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardChatRequest) ProtoMessage() {}

func (x *ForwardChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardChatRequest.ProtoReflect.Descriptor instead.
func (*ForwardChatRequest) Descriptor() ([]byte, []int) {
	return file_grpcserver_proto_ai_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ForwardChatRequest) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ForwardChatRequest) GetRequestBodyJson() string {
	if x != nil {
		return x.RequestBodyJson
	}
	return ""
}

// ForwardChatResponse Chat Completion 转发响应
type ForwardChatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResponseBodyJson string                 `protobuf:"bytes,1,opt,name=response_body_json,json=responseBodyJson,proto3" json:"response_body_json,omitempty"` // AI 厂商的原始 JSON 响应
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ForwardChatResponse) Reset() {
	*x = ForwardChatResponse{}
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardChatResponse) ProtoMessage() {}

func (x *ForwardChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_proto_ai_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardChatResponse.ProtoReflect.Descriptor instead.
func (*ForwardChatResponse) Descriptor() ([]byte, []int) {
	return file_grpcserver_proto_ai_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ForwardChatResponse) GetResponseBodyJson() string {
	if x != nil {
		return x.ResponseBodyJson
	}
	return ""
}

var File_grpcserver_proto_ai_gateway_proto protoreflect.FileDescriptor

const file_grpcserver_proto_ai_gateway_proto_rawDesc = "" +
	"\n" +
	"!grpcserver/proto/ai_gateway.proto\x12\n" +
	"ai_gateway\"y\n" +
	"\rStreamRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x1b\n" +
	"\tconfig_id\x18\x04 \x01(\x03R\bconfigId\"]\n" +
	"\vStreamChunk\x124\n" +
	"\n" +
	"chunk_type\x18\x01 \x01(\x0e2\x15.ai_gateway.ChunkTypeR\tchunkType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\",\n" +
	"\rModelsRequest\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\x03R\bconfigId\"(\n" +
	"\x0eModelsResponse\x12\x16\n" +
	"\x06models\x18\x01 \x03(\tR\x06models\".\n" +
	"\x0fValidateRequest\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\x03R\bconfigId\"F\n" +
	"\x10ValidateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x12ForwardChatRequest\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\x03R\bconfigId\x12*\n" +
	"\x11request_body_json\x18\x02 \x01(\tR\x0frequestBodyJson\"C\n" +
	"\x13ForwardChatResponse\x12,\n" +
	"\x12response_body_json\x18\x01 \x01(\tR\x10responseBodyJson*@\n" +
	"\tChunkType\x12\v\n" +
	"\aCONTENT\x10\x00\x12\r\n" +
	"\tREASONING\x10\x01\x12\r\n" +
	"\tTOOL_CALL\x10\x02\x12\b\n" +
	"\x04DONE\x10\x032\xc8\x02\n" +
	"\tAiGateway\x12F\n" +
	"\x0eGenerateStream\x12\x19.ai_gateway.StreamRequest\x1a\x17.ai_gateway.StreamChunk0\x01\x12M\n" +
	"\x14FetchAvailableModels\x12\x19.ai_gateway.ModelsRequest\x1a\x1a.ai_gateway.ModelsResponse\x12J\n" +
	"\rValidateModel\x12\x1b.ai_gateway.ValidateRequest\x1a\x1c.ai_gateway.ValidateResponse\x12X\n" +
	"\x15ForwardChatCompletion\x12\x1e.ai_gateway.ForwardChatRequest\x1a\x1f.ai_gateway.ForwardChatResponseB\x1dZ\x1bgo-ai-gateway/grpcserver/pbb\x06proto3"

var (
	file_grpcserver_proto_ai_gateway_proto_rawDescOnce sync.Once
	file_grpcserver_proto_ai_gateway_proto_rawDescData []byte
)

func file_grpcserver_proto_ai_gateway_proto_rawDescGZIP() []byte {
	file_grpcserver_proto_ai_gateway_proto_rawDescOnce.Do(func() {
		file_grpcserver_proto_ai_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcserver_proto_ai_gateway_proto_rawDesc), len(file_grpcserver_proto_ai_gateway_proto_rawDesc)))
	})
	return file_grpcserver_proto_ai_gateway_proto_rawDescData
}

var file_grpcserver_proto_ai_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpcserver_proto_ai_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpcserver_proto_ai_gateway_proto_goTypes = []any{
	(ChunkType)(0),              // 0: ai_gateway.ChunkType
	(*StreamRequest)(nil),       // 1: ai_gateway.StreamRequest
	(*StreamChunk)(nil),         // 2: ai_gateway.StreamChunk
	(*ModelsRequest)(nil),       // 3: ai_gateway.ModelsRequest
	(*ModelsResponse)(nil),      // 4: ai_gateway.ModelsResponse
	(*ValidateRequest)(nil),     // 5: ai_gateway.ValidateRequest
	(*ValidateResponse)(nil),    // 6: ai_gateway.ValidateResponse
	(*ForwardChatRequest)(nil),  // 7: ai_gateway.ForwardChatRequest
	(*ForwardChatResponse)(nil), // 8: ai_gateway.ForwardChatResponse
}
var file_grpcserver_proto_ai_gateway_proto_depIdxs = []int32{
	0, // 0: ai_gateway.StreamChunk.chunk_type:type_name -> ai_gateway.ChunkType
	1, // 1: ai_gateway.AiGateway.GenerateStream:input_type -> ai_gateway.StreamRequest
	3, // 2: ai_gateway.AiGateway.FetchAvailableModels:input_type -> ai_gateway.ModelsRequest
	5, // 3: ai_gateway.AiGateway.ValidateModel:input_type -> ai_gateway.ValidateRequest
	7, // 4: ai_gateway.AiGateway.ForwardChatCompletion:input_type -> ai_gateway.ForwardChatRequest
	2, // 5: ai_gateway.AiGateway.GenerateStream:output_type -> ai_gateway.StreamChunk
	4, // 6: ai_gateway.AiGateway.FetchAvailableModels:output_type -> ai_gateway.ModelsResponse
	6, // 7: ai_gateway.AiGateway.ValidateModel:output_type -> ai_gateway.ValidateResponse
	8, // 8: ai_gateway.AiGateway.ForwardChatCompletion:output_type -> ai_gateway.ForwardChatResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpcserver_proto_ai_gateway_proto_init() }
func file_grpcserver_proto_ai_gateway_proto_init() {
	if File_grpcserver_proto_ai_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcserver_proto_ai_gateway_proto_rawDesc), len(file_grpcserver_proto_ai_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcserver_proto_ai_gateway_proto_goTypes,
		DependencyIndexes: file_grpcserver_proto_ai_gateway_proto_depIdxs,
		EnumInfos:         file_grpcserver_proto_ai_gateway_proto_enumTypes,
		MessageInfos:      file_grpcserver_proto_ai_gateway_proto_msgTypes,
	}.Build()
	File_grpcserver_proto_ai_gateway_proto = out.File
	file_grpcserver_proto_ai_gateway_proto_goTypes = nil
	file_grpcserver_proto_ai_gateway_proto_depIdxs = nil
}
